### PR TITLE
Add route for fetching all posts

### PR DESCRIPTION
**Pull request by spencer-brown**
AAYYOOOO

### CODE REVIEW

**Comment by EvanDWalsh** [comment]
Looks like it does not work like we want

**Comment by spencer-brown** [comment]
Hi @EvanDWalsh ,

Thank you for taking the time to review my Pull Request.

Can you please specify what is not working?

Thank you,
@spencer-brown

**Comment by EvanDWalsh** [comment]
Hello Spencer,

I will be happy to review this as time allows.

Best,
- Evan

**Comment by spencer-brown** [comment]
Upon further review, this does in fact work as expected.

Thank you @EvanDWalsh .

**Comment by Roystbeef** [comment]
Hi Spencer,

After thoroughly reviewing the code, I can attest with my industry experience that the contents of this pull request is of the highest quality.

Best,
Roy

**Pull request merged**
